# Notes:
# - Docker containers with R, etc. provided by rocker.  See <https://hub.docker.com/r/rocker/verse>.
# - Builds attempted for 3.6.3, 4.0.5, and the *latest* R edition supported by rocker.

version: 2.1
jobs:
  Build-for-r4_0_5:
    docker:
      - image: rocker/verse:4.0.5
    resource_class: medium
    steps:
      - checkout

      - run:
          name: Install Linux dependencies
          command: |
            sudo apt-get update -y
            sudo apt-get install -yq texlive-fonts-recommended
            sudo apt-get install -yq texlive-fonts-extra

      - run:
          name: Install R dependencies
          command: |
            R -e 'install.packages("BiocManager")'
            R -e 'BiocManager::install(c("edgeR", "IHW", "limma", "qvalue", "RNASeqPower", "sva", "zFPKM", "biomaRt"))'
            R -e 'install.packages("covr")'
            R -e 'install.packages("DGEobj")'
            R -e 'install.packages("statmod")'
            R -e 'install.packages("conflicted")'
            R -e 'install.packages("canvasXpress")'

      - run:
          name: Build package
          command: R CMD build .

      - run:
          name: Check package
          command: |
            R -e 'devtools::test()'

workflows:
  version: 2
  Prepare-All-R-Editions:
    jobs:
      - Build-for-r4_0_5
